// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateSandboxToolRequest struct {
	ToolName             string               `json:"toolName"`
	Description          string               `json:"description,optional"`
	DefaultTimeout       string               `json:"defaultTimeout,optional,default=5m"`
	ClientToken          string               `json:"clientToken,optional"`
	RoleArn              string               `json:"roleArn,optional,default=qcs::cam::uin/100032159895:roleName/sandbox_test"`
	Persistent           bool                 `json:"persistent,optional,default=false"`
	Tags                 []Tag                `json:"tags,optional"`
	NetworkConfiguration NetworkConfiguration `json:"networkConfiguration,optional"`
	CustomConfiguration  CustomConfiguration  `json:"customConfiguration"`
}

type CreateSandboxToolResponse struct {
	Accepted     bool   `json:"accepted"`
	Status       string `json:"status,optional"`
	StatusReason string `json:"statusReason,optional"`
	ErrorCode    string `json:"errorCode,optional"`
	ErrorMessage string `json:"errorMessage,optional"`
	ToolId       string `json:"toolId,optional"`
	RequestId    string `json:"requestId,optional"`
}

type CustomConfiguration struct {
	Image             string                `json:"image"`
	ImageRegistryType string                `json:"imageRegistryType,optional,default=enterprise,options=[enterprise,personal]"`
	Command           []string              `json:"command,optional"`
	Args              []string              `json:"args,optional"`
	Env               []EnvironmentVariable `json:"env,optional"`
	Ports             []PortConfiguration   `json:"ports,optional"`
	Resources         ResourceConfiguration `json:"resources,optional"`
	Probe             ProbeConfiguration    `json:"probe,optional"`
	DnsConfig         DnsConfiguration      `json:"dnsConfig,optional"`
}

type DnsConfiguration struct {
	Servers  []string `json:"servers,optional"`
	Searches []string `json:"searches,optional"`
	Options  []string `json:"options,optional"`
}

type EnvironmentVariable struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type HttpGetAction struct {
	Path   string `json:"path,optional,default=/health"`
	Port   int64  `json:"port,optional,default=49999"`
	Scheme string `json:"scheme,optional,default=HTTP,options=[HTTP,HTTPS]"`
}

type NetworkConfiguration struct {
	NetworkMode string           `json:"networkMode,optional,default=PUBLIC,options=[PUBLIC,VPC,SANDBOX]"`
	VpcConfig   VpcConfiguration `json:"vpcConfig,optional"`
}

type PortConfiguration struct {
	Name     string `json:"name"`
	Protocol string `json:"protocol,options=[TCP]"`
	Port     int64  `json:"port"`
}

type ProbeConfiguration struct {
	HttpGet          HttpGetAction `json:"httpGet,optional"`
	ReadyTimeoutMs   int64         `json:"readyTimeoutMs,optional,default=30000"`
	ProbeTimeoutMs   int64         `json:"probeTimeoutMs,optional,default=1000"`
	ProbePeriodMs    int64         `json:"probePeriodMs,optional,default=1000"`
	SuccessThreshold int64         `json:"successThreshold,optional,default=1"`
	FailureThreshold int64         `json:"failureThreshold,optional,default=100"`
}

type ResourceConfiguration struct {
	CPU    string `json:"cpu,optional,default=1"`
	Memory string `json:"memory,optional,default=2Gi"`
}

type SyncImageData struct {
	Image   string `json:"image"`
	NewSync bool   `json:"newSync"`
	Time    int64  `json:"time"`
}

type SyncImageRequest struct {
	SrcHub string `form:"srcHub"`
	DstHub string `form:"dstHub"`
	Group  string `form:"group"`
	Image  string `form:"image"`
	Tag    string `form:"tag"`
}

type SyncImageResponse struct {
	Code   int64         `json:"code"`
	Data   SyncImageData `json:"data"`
	Status string        `json:"status"`
}

type Tag struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type VpcConfiguration struct {
	SubnetIds        []string `json:"subnetIds,optional"`
	SecurityGroupIds []string `json:"securityGroupIds,optional"`
}
