// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CosStorageSource struct {
	Endpoint   string `json:"endpoint,optional"`
	BucketName string `json:"bucketName,optional"`
	BucketPath string `json:"bucketPath,optional"`
}

type CreateSandboxToolRequest struct {
	ToolName             string               `json:"toolName"`
	Description          string               `json:"description,optional"`
	DefaultTimeout       string               `json:"defaultTimeout,optional"`
	ClientToken          string               `json:"clientToken,optional"`
	RoleArn              string               `json:"roleArn,optional"`
	Persistent           *bool                `json:"persistent,optional"`
	Tags                 []Tag                `json:"tags,optional"`
	NetworkConfiguration NetworkConfiguration `json:"networkConfiguration,optional"`
	StorageMounts        []StorageMount       `json:"storageMounts,optional"`
	CustomConfiguration  CustomConfiguration  `json:"customConfiguration"`
}

type CreateSandboxToolResponse struct {
	Accepted     bool   `json:"accepted"`
	Status       string `json:"status,optional"`
	StatusReason string `json:"statusReason,optional"`
	ErrorCode    string `json:"errorCode,optional"`
	ErrorMessage string `json:"errorMessage,optional"`
	ToolId       string `json:"toolId,optional"`
	RequestId    string `json:"requestId,optional"`
}

type CustomConfiguration struct {
	Image             string                `json:"image"`
	ImageRegistryType string                `json:"imageRegistryType,optional,options=[enterprise,personal]"`
	Command           []string              `json:"command,optional"`
	Args              []string              `json:"args,optional"`
	Env               []EnvironmentVariable `json:"env,optional"`
	Ports             []PortConfiguration   `json:"ports,optional"`
	Resources         ResourceConfiguration `json:"resources,optional"`
	Probe             ProbeConfiguration    `json:"probe,optional"`
	DnsConfig         DnsConfiguration      `json:"dnsConfig,optional"`
}

type DnsConfiguration struct {
	Servers  []string `json:"servers,optional"`
	Searches []string `json:"searches,optional"`
	Options  []string `json:"options,optional"`
}

type EnvironmentVariable struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type GetSandboxToolStatusRequest struct {
	ToolId string `form:"toolId"`
}

type GetSandboxToolStatusResponse struct {
	ToolId       string `json:"toolId"`
	Status       string `json:"status"`
	StatusReason string `json:"statusReason,optional"`
	RequestId    string `json:"requestId,optional"`
}

type HttpGetAction struct {
	Path   string `json:"path,optional"`
	Port   int64  `json:"port,optional"`
	Scheme string `json:"scheme,optional,options=[HTTP,HTTPS]"`
}

type NetworkConfiguration struct {
	NetworkMode string           `json:"networkMode,optional,options=[PUBLIC,VPC,SANDBOX]"`
	VpcConfig   VpcConfiguration `json:"vpcConfig,optional"`
}

type PortConfiguration struct {
	Name     string `json:"name"`
	Protocol string `json:"protocol,options=[TCP]"`
	Port     int64  `json:"port"`
}

type ProbeConfiguration struct {
	HttpGet          HttpGetAction `json:"httpGet,optional"`
	ReadyTimeoutMs   int64         `json:"readyTimeoutMs,optional"`
	ProbeTimeoutMs   int64         `json:"probeTimeoutMs,optional"`
	ProbePeriodMs    int64         `json:"probePeriodMs,optional"`
	SuccessThreshold int64         `json:"successThreshold,optional"`
	FailureThreshold int64         `json:"failureThreshold,optional"`
}

type ResourceConfiguration struct {
	CPU    string `json:"cpu,optional"`
	Memory string `json:"memory,optional"`
}

type StorageMount struct {
	Name          string        `json:"name,optional"`
	StorageSource StorageSource `json:"storageSource,optional"`
	MountPath     string        `json:"mountPath,optional"`
	ReadOnly      *bool         `json:"readOnly,optional"`
}

type StorageSource struct {
	Cos CosStorageSource `json:"cos,optional"`
}

type SyncImageData struct {
	Image   string `json:"image"`
	NewSync bool   `json:"newSync"`
	Time    int64  `json:"time"`
}

type SyncImageRequest struct {
	SrcHub string `form:"srcHub"`
	DstHub string `form:"dstHub"`
	Group  string `form:"group"`
	Image  string `form:"image"`
	Tag    string `form:"tag"`
}

type SyncImageResponse struct {
	Code   int64         `json:"code"`
	Data   SyncImageData `json:"data"`
	Status string        `json:"status"`
}

type Tag struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type VpcConfiguration struct {
	SubnetIds        []string `json:"subnetIds,optional"`
	SecurityGroupIds []string `json:"securityGroupIds,optional"`
}
