// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	cubeSandboxImage "github.com/TencentCloudAgentRuntime/ags-cookbook/examples/custom-image-go-sdk/cube_sandbox_image_server/internal/handler/cubeSandboxImage"
	"github.com/TencentCloudAgentRuntime/ags-cookbook/examples/custom-image-go-sdk/cube_sandbox_image_server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 将镜像从源镜像仓库同步到目标镜像仓库
				Method:  http.MethodGet,
				Path:    "/images/sync",
				Handler: cubeSandboxImage.SyncImageHandler(serverCtx),
			},
			{
				// 创建腾讯云自定义沙箱工具
				Method:  http.MethodPost,
				Path:    "/sandbox/tools",
				Handler: cubeSandboxImage.CreateSandboxToolHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
